HANDLING MISSING DATA:-----

In [1]:
import numpy as np
import pandas as pd

CREATE DATASET

In [3]:
data={
    'student_id':[1,2,3,4,5,6],
    'marks':[78,82,83,np.nan,90,95],
    'income':[20000,25000,32000,np.nan,46000,np.nan],
    'city':['delhi','mumbai',np.nan,'delhi','lucknow','delhi']
}

CONVERT DATA IN DATAFRAME

In [5]:
df=pd.DataFrame(data)

NOW, CHECK THE DATA AND FIND THE TOTAL MISSING VALUES

In [11]:
df.head(6)

   student_id  marks   income     city
0           1   78.0  20000.0    delhi
1           2   82.0  25000.0   mumbai
2           3   83.0  32000.0      NaN
3           4    NaN      NaN    delhi
4           5   90.0  46000.0  lucknow
5           6   95.0      NaN    delhi

In [10]:
df.isnull().sum()

student_id    0
marks         1
income        2
city          1
dtype: int64

WE CAN ERASE ALL THE ROW THAT CONTAINS MISSING VALUES BUT NOT SUITABLE FOR SMALLER DATA:-----

In [14]:
df_dropped=df.dropna()
print('DataFrame after dropping values')
df_dropped.head(6)

DataFrame after dropping values

   student_id  marks   income     city
0           1   78.0  20000.0    delhi
1           2   82.0  25000.0   mumbai
4           5   90.0  46000.0  lucknow

WE CAN USE STATISTICAL METHOD LIKE MEAN, MEADIAN, MODE OR ELSE:-----

HERE WE ALL TAKE THE PREVIOUS DATAFRAME BY COPYING IT

In [16]:
df_new=df.copy()

In [17]:
df_new.head(6)

   student_id  marks   income     city
0           1   78.0  20000.0    delhi
1           2   82.0  25000.0   mumbai
2           3   83.0  32000.0      NaN
3           4    NaN      NaN    delhi
4           5   90.0  46000.0  lucknow
5           6   95.0      NaN    delhi

In [24]:
df_new['marks']=df_new['marks'].fillna(df_new['marks'].median())
df_new['income']=df_new['income'].fillna(df_new['income'].mean())
df_new['city']=df_new['city'].fillna(df_new['city'].mode()[0])

In [25]:
df_new.head(6)

   student_id  marks   income     city
0           1   78.0  20000.0    delhi
1           2   82.0  25000.0   mumbai
2           3   83.0  32000.0    delhi
3           4   85.6  30750.0    delhi
4           5   90.0  46000.0  lucknow
5           6   95.0  30750.0    delhi