# Target Guided Ordinal Encoding:----

In [2]:
import pandas as pd

1. Create a sample DataFrame with a categorical feature ('City') and target ('price')

In [3]:
data={
    'City':['New York', 'London', 'Paris', 'Tokyo', 'New York', 'Paris'],
    'price':[200, 150, 300, 250, 180, 320]
}

In [13]:
df=pd.DataFrame(data)
df.head()

       city  price
0  New York    200
1    London    150
2     Paris    300
3     Tokyo    250
4  New York    180

2. Calculate mean target price for each city

In [16]:
mean_price=df.groupby('city')['price'].mean()
df['city_encoded'] = df['city'].map(mean_price)

In [18]:
print("--- Target Guided Ordinal Encoded DataFrame ---")
df

--- Target Guided Ordinal Encoded DataFrame ---

       city  price  city_encoded
0  New York    200         190.0
1    London    150         150.0
2     Paris    300         310.0
3     Tokyo    250         250.0
4  New York    180         190.0
5     Paris    320         310.0